In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    StratifiedKFold,
    GridSearchCV,
    RandomizedSearchCV
)

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_curve,
    roc_auc_score,
    classification_report
)

import joblib

In [3]:
df = pd.read_csv(
    r"C:\Users\sujee\Desktop\Heart_disease prediction1\Heart_Disease_Prediction.csv"
)

# 7. Train-Test Split and Data Preprocessing

Before training Machine Learning models, the dataset is prepared by encoding the target variable, separating the features and target, and splitting the data into training and testing sets.

The training data is used to train the models, while the testing data is used to evaluate performance on unseen data.

Target Encoding

In [4]:
print(df["Heart Disease"].value_counts(dropna=False))

Heart Disease
Absence     150
Presence    120
Name: count, dtype: int64


In [5]:
df["Heart Disease"] = df["Heart Disease"].map({
    "Absence": 0,
    "Presence": 1
})

In [6]:
print("Target column:")
print(df["Heart Disease"].head())

print("\nTarget data type:")
print(df["Heart Disease"].dtype)

print("\nTarget value counts:")
print(df["Heart Disease"].value_counts())

Target column:
0    1
1    0
2    1
3    0
4    0
Name: Heart Disease, dtype: int64

Target data type:
int64

Target value counts:
Heart Disease
0    150
1    120
Name: count, dtype: int64


In [7]:
print(df["Heart Disease"].value_counts(dropna=False))

print(
    "Missing values:",
    df["Heart Disease"].isna().sum()
)

Heart Disease
0    150
1    120
Name: count, dtype: int64
Missing values: 0


## Separate X and y

The target column `Heart Disease` is separated from the input features.

- `X` contains the 13 input features.
- `y` contains the target variable.

In [8]:
X = df.drop("Heart Disease", axis=1)

y = df["Heart Disease"]

In [9]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (270, 13)
y shape: (270,)


Train-Test Split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [11]:
print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTraining data:")
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("\nTesting data:")
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X shape: (270, 13)
y shape: (270,)

Training data:
X_train: (216, 13)
y_train: (216,)

Testing data:
X_test: (54, 13)
y_test: (54,)


Data Preprocessing

# 8. Data Preprocessing

### Encoding

The categorical target variable `Heart Disease` contains the classes `Absence` and `Presence`.

These classes are encoded as:

- `Absence` → 0
- `Presence` → 1

The input features in this dataset are already represented using numerical codes, so separate feature encoding is not required.

## Pipeline

A Machine Learning pipeline is used to combine preprocessing and model training into a single workflow.

`StandardScaler` is used to standardize numerical features before Logistic Regression.

In [12]:
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=2000))
])

In [13]:
pipeline.fit(X_train, y_train)

,steps,"[('scaler', ...), ('model', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0


In [14]:
y_pred = pipeline.predict(X_test)

y_prob = pipeline.predict_proba(X_test)[:, 1]

In [15]:
from sklearn.metrics import accuracy_score

y_train_pred = pipeline.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_pred)

y_test_pred = pipeline.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)

print("Training Accuracy:", train_accuracy)
print("Testing Accuracy:", test_accuracy)

Training Accuracy: 0.8518518518518519
Testing Accuracy: 0.8518518518518519


# 9. Handling Imbalance

The class distribution of the target variable is checked to determine whether oversampling or undersampling is required.

In [16]:
print(y.value_counts())

print(
    y.value_counts(normalize=True) * 100
)

Heart Disease
0    150
1    120
Name: count, dtype: int64
Heart Disease
0    55.555556
1    44.444444
Name: proportion, dtype: float64


The target variable is reasonably balanced, with 55.56% samples in class 0 and 44.44% samples in class 1.

The difference is approximately 11.11 percentage points.

Therefore, no oversampling or undersampling technique was required for this dataset.